import { Header } from '@/components/shared/main/header/header'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'

const geistSans = Nunito({
	subsets: ['cyrillic'],
	variable: '--font-nunito',
	weight: ['400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<meta name='viewport' content='width=device-width, initial-scale=1.0' />
			<body className={`${geistSans.variable} antialiased`}>
				<main className='min-h-screen'>
					<Header />
					{children}
				</main>
			</body>
		</html>
	)
}
